# Generated by Django 4.2 on 2026-07-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_director_id_alter_pelicula_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='tipo',
            field=models.CharField(choices=[('DIGITAL', 'Digital'), ('MULTICINES', 'Multicines'), ('YOUTUBE', 'YouTube'), ('NETFLIX', 'Netflix'), ('AMAZON', 'Amazon Prime Video'), ('DISNEY', 'Disney+'), ('FISICO', 'Físico')], max_length=20),
        ),
    ]
