# Generated by Django 4.2 on 2026-07-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_director_fecha_nacimiento_alter_vendedor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(choices=[('ACCION', 'Acción'), ('COMEDIA', 'Comedia'), ('DRAMA', 'Drama'), ('TERROR', 'Terror'), ('CIENCIA_FICCION', 'Ciencia Ficción'), ('ANIMACION', 'Animación'), ('DOCUMENTAL', 'Documental'), ('ROMANCE', 'Romance'), ('AVENTURA', 'Aventura'), ('FANTASIA', 'Fantasía'), ('MUSICAL', 'Musical'), ('SUSPENSE', 'Suspense'), ('WESTERN', 'Western')], default='DRAMA', max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='vendedores',
            field=models.ManyToManyField(blank=True, related_name='peliculas', to='catalog.vendedor'),
        ),
    ]
