# Generated by Django 4.2 on 2026-07-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pelicula_genero_alter_pelicula_vendedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
